name: Build Android APK

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./

    - name: Build with Gradle
      run: ./gradlew assembleRelease
      working-directory: ./

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: exploit-apk
        path: app/build/outputs/apk/release/app-release.apk
